[log]
reporter_type = 'proxy'
reporter_name = 'debug_proxy'
file_path = 'oset.log'
max_file_size = 10
max_backups = 5
max_age = 30
is_compress = false

[log.kafka]
is_enable = true
host = '127.0.0.1:9092'
topic = 'log'

[mysql]
host = 'localhost'
port = '3306'
database = 'oset'
charset = 'utf8'
loc = 'Asia/Shanghai'
user = 'root'
password = '123456'

[kafka]
host = '127.0.0.1:9092'

[sys]
name = 'proxy'
inited = false
