[log]
compress = false
logpath = 'oset.log'
maxage = 30
maxbackups = 5
maxsize = 10

[mysql]
host = 'localhost'
port = '3306'
database = 'oset'
charset = 'utf8'
loc = 'Asia/Shanghai'
user = 'root'
password = '123456'

[kafka]
host = '127.0.0.1'
port = '9092'

[sys]
name = 'proxy'
inited = false
